"""empty message

Revision ID: ea1dfbecd7b9
Revises: 81a0865590b0
Create Date: 2024-11-29 12:05:43.591595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1dfbecd7b9'
down_revision = '81a0865590b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefecture_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('city_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('city_code')
        batch_op.drop_column('prefecture_id')

    # ### end Alembic commands ###
